# Generated by Django 4.0.2 on 2022-09-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='title',
            field=models.CharField(blank=True, default='no title', max_length=150),
        ),
    ]
