# Generated by Django 4.0.2 on 2022-09-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptapp', '0002_alter_prompt_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
