# Generated by Django 4.0.2 on 2022-09-07 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promptapp', '0003_alter_prompt_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='created',
        ),
    ]
