# Generated by Django 4.0.2 on 2022-09-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptapp', '0004_remove_prompt_completed_remove_prompt_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
